app_vm_name = "Gateway01"
app_name = "Gateway01"
app_ip = "192.168.1.1"
app_netmask = "255.255.255.0"

Vagrant.configure("2") do |conf|

conf.vm.box = "debian/stretch64"

conf.vm.define app_name
  conf.vm.provider :virtualbox do |vb|
    vb.name = app_vm_name
  end

conf.vm.hostname = app_name
conf.vm.network "private_network", ip: app_ip, netmask: app_netmask, virtualbox__intnet: true

conf.vm.provision "chef_solo" do |chef|
    chef.cookbooks_path = "../chef-repo/cookbooks"
    chef.roles_path = "../chef-repo/roles"
    chef.json = {
      :route => {
        :ip_gateway => "10.0.2.2",
        :device => "eth0"
      }
    }
    chef.add_recipe "router"
  end
end
