#!/bin/sh

PATH=/usr/sbin:/sbin:/bin:/usr/bin

lan="eth1"
web="eth2"

#
# delete all existing rules.
#
iptables -F
iptables -t nat -F
iptables -t mangle -F
iptables -X

# Always accept loopback traffic
iptables -A INPUT -i lo -j ACCEPT

# Allow established connections, and those not coming from the outside
iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A INPUT -m state --state NEW ! -i "$web" -j ACCEPT
iptables -A FORWARD -i "$web" -o "$lan" -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A FORWARD -i "$lan" -p tcp --dport 80 -d 192.168.254.250 -j ACCEPT

# Allow outgoing connections from the LAN side.
iptables -A FORWARD -i "$lan" -o "$web" -j ACCEPT

# Masquerade.
iptables -t nat -A POSTROUTING -o "$web" -j MASQUERADE

# Don't forward from the outside to the inside.
iptables -A FORWARD -i "$web" -o "$web" -j REJECT

# Enable routing.
echo 1 > /proc/sys/net/ipv4/ip_forward
