# -*- mode: ruby -*-
# vi: set ft=ruby :

GATEWAY = exec 'netstat -rn | grep 192.168 | grep default | tr -s " " | cut -d" " -f 2'

app_vm_name = "devops-Gateway"
app_name = "gateway"
app_ip = "192.168.254.249"
app_netmask = "255.255.255.248"

Vagrant.configure(2) do |conf|
  conf.vm.box = "jubianchi/debian-wheezy-chef-i386"

  conf.vm.define app_name
  conf.vm.provider :virtualbox do |vb|
    vb.name = app_vm_name
  end

  conf.vm.hostname = app_name
  conf.vm.network "private_network", ip: app_ip, netmask: app_netmask
  conf.vm.network "public_network"

  conf.vm.provision "chef_solo" do |chef|
    chef.cookbooks_path = "../chef-repo/cookbooks"
    chef.roles_path = "../chef-repo/roles"
    chef.json = {
      :route => {
        :ip_gateway => GATEWAY,
        :device => "eth2"
      }
    }
    chef.add_recipe "default-route"
    chef.add_recipe "router"
  end
end
