# -*- mode: ruby -*-
# vi: set ft=ruby :


app_vm_name = "Web01"
app_name = "Web01"
app_ip = "192.168.1.2"
app_netmask = "255.255.255.0"
app_ip_gateway = "192.168.1.1
app_docroot = "./web1_docroot"

Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"

  conf.vm.define app_name
  conf.vm.provider :virtualbox do |vb|
    vb.name = app_vm_name
  end

  conf.vm.hostname = app_name
  conf.vm.synced_folder app_docroot, "/var/www", :mount_options => ["dmode=777", "fmode=666"]

  conf.vm.network "private_network", ip: app_ip, netmask: app_netmask

  conf.vm.provision "chef_solo" do |chef|
    chef.cookbooks_path = "../chef-repo/cookbooks"
    chef.roles_path = "../chef-repo/roles"
    chef.json = {
      :route => {
        :ip_gateway => app_ip_gateway
      }
    }
    chef.add_role("web-server")
  end
end
