# -*- mode: ruby -*-
# vi: set ft=ruby :

app_vm_name = "Proxy"
app_name = "Proxy"
app_ip = "192.168.1.4"
app_netmask = "255.255.255.0"
app_ip_gateway = "192.168.1.1

Vagrant.configure("2") do |conf|
  conf.vm.box = "debian/stretch64"

  conf.vm.define app_name
  conf.vm.provider :virtualbox do |vb|
    vb.name = app_vm_name
  end

  conf.vm.hostname = app_name
  conf.vm.network "private_network", ip: app_ip, netmask: app_netmask
  conf.vm.network "forwarded_port", guest: 80, host: 8042

  conf.vm.provision "chef_solo" do |chef|
    chef.cookbooks_path = "../chef-repo/cookbooks"
    chef.roles_path = "../chef-repo/roles"
    chef.json = {
      :route => {
        :ip_gateway => app_ip_gateway
      }
    }
    chef.add_recipe "nginx"
    chef.add_recipe "default-route"
    chef.add_role("load-balancing")
  end
end
